# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [5]:
from operator import length_hint

import pandas as pd
import numpy as np

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [6]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame({
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
})

df

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [7]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [8]:
df["Salary"] = [50000, 60000, 45000]
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [18]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [9]:
from datetime import datetime

curr_year = datetime.now().year
df["Birth year"] = curr_year - df["Age"]
df

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2009
1  Emily   28  Los Angeles   60000        1997
2   Ryan   22      Chicago   45000        2003

### Task 4.2

Add new calculated field `Average age`.

In [10]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [11]:
df["Absolute difference"] = abs(df["Age"] - df["Average age"])
df

,Name,Age,City,Salary,Birth year,Average age,Absolute difference
0,John,16,New York,50000,2009,22.0,6.0
1,Emily,28,Los Angeles,60000,1997,22.0,6.0
2,Ryan,22,Chicago,45000,2003,22.0,0.0

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [14]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data1)

df2 = pd.DataFrame(data2)

In [15]:
# merge
merge_df = pd.merge(df1, df2, on="Name", how="inner")
merge_df

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [34]:
# concatenate
concatenate_df = pd.concat([df1, df2], axis=0)
concatenate_df

    Name  Age
0   John   25
1  Emily   28
2   Ryan   22
0   John   25
1  Emily   28
2   Ryan   22

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [7]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [8]:
# use + operator here
add_s = s1 + s2
add_s

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [10]:
# use - operator here
subtraction = s1 - s2
subtraction

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [11]:
# use * operator here
multiply = s1 * s2
multiply

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [12]:
# use / operator here
divide = s1 / s2
divide

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

In [13]:
# use ** operator here
square = s1 ** s2
square

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [14]:
# use // operator here
division = s1 // s2
division

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [15]:
# use % operator here
modulus = s1 % s2
modulus

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
# filter s1 here
even = s1 % 2 == 0
s1[even]

1    2
3    4
dtype: int64

In [23]:
# filter s2 here
odd = s2 % 2 != 0
s2[odd]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [17]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [20]:
# make all words in uppercase
upper = s.str.upper()
upper

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [31]:
# get length of each word
length_w = s.str.len()
length_w

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [32]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 5.81 s
Wall time: 5.93 s

[61.0, 60.0, 65.2, 63.0, 60.6, 48.2, 35.6, 40.6, 31.4, 36.8]

### Solution using Pandas and Numpy

In [37]:
# write your code here
data = pd.Series([random.randint(1, 100) for _ in range(10000000)])
moving_averages = data.rolling(window=5).mean().dropna()
moving_averages[:10]

4     49.4
5     45.4
6     46.6
7     48.4
8     48.8
9     46.6
10    52.4
11    62.2
12    58.0
13    48.8
dtype: float64